import { z } from "zod";
import type { Option, Ref } from "effect";
import type { Action } from "@betalyra/generative-ui-common/client";
import type { ManagedSandbox } from "../sandbox/manager.js";

// ============================================================
// Zod Schemas
// ============================================================

export const PatchSchema = z.union([
  z.object({ selector: z.string(), text: z.string() }),
  z.object({
    selector: z.string(),
    attr: z.record(z.string(), z.string().nullable()),
  }),
  z.object({ selector: z.string(), append: z.string() }),
  z.object({ selector: z.string(), prepend: z.string() }),
  z.object({ selector: z.string(), html: z.string() }),
  z.object({ selector: z.string(), remove: z.literal(true) }),
]);

export const PatchArraySchema = z.array(PatchSchema);

// Code module summary — emitted by LLM at end of stream
export const CodeModuleSummarySchema = z.object({
  path: z.string(),
  description: z.string(),
  exports: z.array(z.string()),
  usage: z.string(),
});

export type CodeModuleSummary = z.infer<typeof CodeModuleSummarySchema>;

// Schema for LLM responses
export const LLMResponseSchema = z.union([
  z.object({
    type: z.literal("patches"),
    patches: PatchArraySchema,
  }),
  z.object({
    type: z.literal("full"),
    html: z.string(),
  }),
  z.object({
    type: z.literal("code_modules"),
    modules: z.array(CodeModuleSummarySchema),
  }),
]);

// Full response schema includes stats (generated by code, not LLM)
export const UnifiedResponseSchema = z.union([
  LLMResponseSchema,
  z.object({
    type: z.literal("stats"),
    cacheRate: z.number(),
    tokensPerSecond: z.number(),
    mode: z.enum(["patches", "full"]),
    patchCount: z.number(),
  }),
]);

// ============================================================
// Exported Types
// ============================================================

export type UnifiedResponse = z.infer<typeof UnifiedResponseSchema>;

export type UnifiedGenerateOptions = {
  sessionId: string;
  currentHtml?: string;
  actions: readonly Action[];
  modelId?: string;
  sandboxRef?: Ref.Ref<Option.Option<ManagedSandbox>>;
};

// ============================================================
// Retry Types - Immutable state for functional retry loop
// ============================================================

export type Message = {
  readonly role: "system" | "user" | "assistant";
  readonly content: string;
};


// Usage types for token aggregation
export type Usage = {
  inputTokens?: number;
  outputTokens?: number;
  totalTokens?: number;
  inputTokenDetails?: { cacheReadTokens?: number };
};

export type AggregatedUsage = {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cachedTokens: number;
};
